### ISSUE TITLE
missing module in libro2

### ISSUE THREAD

**Issue by docjc** [dnkorpushov/libro2#2]
hi,
I installed Libro2  as mentioned in your description getting the info "unhandled exception in script" and found in warn-libro2.txt 
the same info: "missing module named darkdetect - imported by ui.maintoolbar (top-level)"

![grafik](https://user-images.githubusercontent.com/108517885/193841584-2c3c4276-d774-4f74-9571-24ad4719e611.png)

These modules are installed:

d:\Python\ebookmeta\libro2\dist\libro2>pip freeze
altgraph==0.17.3
ebookmeta==1.2.8
future==0.18.2
lxml==4.9.1
pefile==2022.5.30
pyinstaller==5.4.1
pyinstaller-hooks-contrib==2022.10
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
pywin32-ctypes==0.2.0

What to do???

**Comment by dnkorpushov** [comment]
I am sorry. The new version of the program has an additional dependency from the darkdetect Python module. I have correct the guide.
You can just install darkdetect module:
pip install darkdetect  
or 
pip install --user darkdetect

**Comment by docjc** [comment]
Thank you , now it works fine ;)
One more question: would it be possible to add the possibilizy to change the description text of the epub, just as plain text?? 
rgds
